feed_cache:
  defaults:
    ttl_hours: 24

  ttl_hours:
    exploit_db: 24
    kev: 24
    epss: 6

    # NVD TTLs
    nvd_yearly: 24
    mvd_modified: 2

  nvd:
    enabled: true
    start_year: 2023
    end_year: 2025