import hashlib
import re
from dataclasses import dataclass
from typing import Optional

_WS = re.compile(r"\s+")
_PUNT = re.compile(r"[^a-z0-9:/._-]+")

def _sha16(s: str) -> str:
    return hashlib.sha256(s.encode("utf-8")).hexdigest()[:16]

def norm_text(s: Optional[str], max_len: int = 80) -> str:
    if not s:
        return "-"
    s = s.strip().lower()
    s = _WS.sub(" ", s)
    s = _PUNT.sub("", s)
    return s[:max_len] if len(s) > max_len else s

def norm_ip(s: Optional[str]) -> str:
    return (s or "").strip()

def norm_proto(s: Optional[str]) -> str:
    s = (s or "").strip().lower()
    if s in ("tcp", "udp", "icmp"):
        return s
    return "unknown"

def norm_port(p) -> str:
    try:
        i = int(p)
        return str(i if i >= 0 else 0)
    except Exception:
        return "0"

def make_asset_id(ip: Optional[str], hostname: Optional[str]) -> str:
    """
    Creates canonical asset_ids
    """
    canon = f"vpp:asset:v1|ip={norm_ip(ip) or '-'}|host={norm_text(hostname, 120)}"
    return "aid_v1_" + _sha16(canon)

def make_finding_base_canon(
    asset_id: str,
    scanner_sig: str,
    proto: str,
    port: str,
    kind: str
) -> str:
    """
    Generates base str value for passing into make_finding_id

    :param asset_id: asset_id generated by make_asset_id helper.
    :type asset_id: str
    :param scanner_sig: ParserName: + pluginid | oid
    :type scanner_sig: str
    :param proto: protocol (tcp/udp)
    :type proto: str
    :param port: port str(int)
    :type port: str
    :param kind: Scanner pluginname | nvt name
    :type kind: str
    :return: Unique base canonical string used for generating Finding IDs
    :rtype: str
    """
    return (
        "vpp:finding:v1|"
        f"asset={asset_id}|"
        f"sig={scanner_sig}|"
        f"svc={proto}:{port}|"
        f"kind={kind}"
    )

def make_finding_id(canon: str) -> str:
    """
    Generates a unique Finding_ID #

    :param canon: Canoncial Base returned by make_finding_base_canon.
    :type canon: str
    :return: Finding ID
    :rtype: str
    """
    return "fid_v1_" + _sha16(canon)
