"""Centralized reason code registry for DecisionLedger events."""


class DecisionReasonCodes:
    PASS_EXECUTION_STARTED = "PASS_EXECUTION_STARTED"
    PASS_EXECUTION_COMPLETED = "PASS_EXECUTION_COMPLETED"
    PASS_EXECUTION_FAILED = "PASS_EXECUTION_FAILED"

    ENRICHMENT_PHASE_STARTED = "ENRICHMENT_PHASE_STARTED"
    ENRICHMENT_PHASE_COMPLETED = "ENRICHMENT_PHASE_COMPLETED"

    SCORING_SUMMARY_COMPUTED = "SCORING_SUMMARY_COMPUTED"
    HIGHEST_RISK_ASSET_SELECTED = "HIGHEST_RISK_ASSET_SELECTED"
    ASSET_CRITICALITY_DERIVED = "ASSET_CRITICALITY_DERIVED"

    TOPN_RANKING_COMPLETED = "TOPN_RANKING_COMPLETED"
    TOP_ASSET_SELECTED = "TOP_ASSET_SELECTED"
    EXPOSURE_INFERENCE_SUMMARY = "EXPOSURE_INFERENCE_SUMMARY"
    TOPN_SKIPPED_MISSING_SCORING = "TOPN_SKIPPED_MISSING_SCORING"
    TOPN_SKIPPED_MISSING_ACI = "TOPN_SKIPPED_MISSING_ACI"
    TOPN_ACI_UPLIFT_APPLIED = "TOPN_ACI_UPLIFT_APPLIED"

    NMAP_CTX_DISABLED = "NMAP_CTX_DISABLED"
    NMAP_CTX_ENABLED = "NMAP_CTX_ENABLED"
    NMAP_CTX_FAILED = "NMAP_CTX_FAILED"
    NMAP_CTX_INVALID_FORMAT = "NMAP_CTX_INVALID_FORMAT"

    ACI_INFERENCE_SUMMARY = "ACI_INFERENCE_SUMMARY"
    ACI_FINDING_INFERRED = "ACI_FINDING_INFERRED"

    WEBHOOK_EMIT_STARTED = "WEBHOOK_EMIT_STARTED"
    WEBHOOK_EMIT_SUCCEEDED = "WEBHOOK_EMIT_SUCCEEDED"
    WEBHOOK_EMIT_FAILED = "WEBHOOK_EMIT_FAILED"
    WEBHOOK_EMIT_SKIPPED_DISABLED = "WEBHOOK_EMIT_SKIPPED_DISABLED"
    WEBHOOK_EMIT_SKIPPED_POLICY = "WEBHOOK_EMIT_SKIPPED_POLICY"
    WEBHOOK_EMIT_SPOOLED_FOR_RETRY = "WEBHOOK_EMIT_SPOOLED_FOR_RETRY"

    INGESTION_ROWS_DROPPED = "INGESTION_ROWS_DROPPED"
    INGESTION_MALFORMED_ROWS_SKIPPED = "INGESTION_MALFORMED_ROWS_SKIPPED"
    INGESTION_STRICT_REJECTED = "INGESTION_STRICT_REJECTED"
    INGESTION_CONFIDENCE_THRESHOLD_FAILED = "INGESTION_CONFIDENCE_THRESHOLD_FAILED"
