"""Centralized reason code registry for DecisionLedger events."""


class DecisionReasonCodes:
    PASS_EXECUTION_STARTED = "PASS_EXECUTION_STARTED"
    PASS_EXECUTION_COMPLETED = "PASS_EXECUTION_COMPLETED"
    PASS_EXECUTION_FAILED = "PASS_EXECUTION_FAILED"

    ENRICHMENT_PHASE_STARTED = "ENRICHMENT_PHASE_STARTED"
    ENRICHMENT_PHASE_COMPLETED = "ENRICHMENT_PHASE_COMPLETED"

    SCORING_SUMMARY_COMPUTED = "SCORING_SUMMARY_COMPUTED"
    HIGHEST_RISK_ASSET_SELECTED = "HIGHEST_RISK_ASSET_SELECTED"
    ASSET_CRITICALITY_DERIVED = "ASSET_CRITICALITY_DERIVED"

    TOPN_RANKING_COMPLETED = "TOPN_RANKING_COMPLETED"
    TOP_ASSET_SELECTED = "TOP_ASSET_SELECTED"
    EXPOSURE_INFERENCE_SUMMARY = "EXPOSURE_INFERENCE_SUMMARY"
    TOPN_SKIPPED_MISSING_SCORING = "TOPN_SKIPPED_MISSING_SCORING"
